name: abstractdb
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  signals: ^6.0.2
  initializable:
    path: /Users/jessica/Projects/dart_packages/initializable
  collql:
    path: /Users/jessica/Projects/dart_packages/collql
  hive: ^2.2.3
  async: ^2.13.0
  fuzzy: ^0.5.1
  supabase: ^2.6.3
  xid: ^1.2.1
  embed_annotation: ^1.2.2
  http: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.15
  embed: ^1.4.1
  lints: ^5.0.0
  test: ^1.24.0
